name: Run Tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: xdebug

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Prepare application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        run: |
          vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no
          php artisan test --parallel
